### PR TITLE
feat: enable eol-last, no-trailing-spaces, array-bracket-spacing

### PR DESCRIPTION
**Pull request by ripecosta**
Description

Enable the `eol-last`, `no-trailing-spaces` and `array-bracket-spacing` ESLint rules. 

- `eol-last`:  Causes ESlint to require a single empty line at the end of files.
- `no-trailing-spaces`: Causes ESLint to trim trailing spaces.
- `array-bracket-spacing`: Causes ESLint to remove spaces at the start and at the end of arrays. We have been using the opposite rule up to now (always rather than never) but this is more inline with the rest of our config, where we remove dead space between code.

### CODE REVIEW

**Comment by ricca509** [comment]
I thought we'd decided to move away from bending eslint to be a formatter and moved on (or in the process of moving on) to different tools?

**Comment by ricca509** [comment]
@rahulk94

**Comment by ripecosta** [comment]
@ricca509 We did. But since there's a significant number of projects that haven't migrated yet I figured this would still be useful.

**Review by l1fe — APPROVED** [review]

**Comment by rahulk94** [comment]
Was off but yes @ricca509 - BiomeJS is the replacement we should be moving to

**Pull request merged**
